config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'show/show'
  resources :search
  resources :home
  resources :carts
  resources :orders, only: [:index,:create ,:delete]


  get 'about', to: 'home#about', as: :about
  get 'contact',to: 'home#contact',as: :contact
  get 'checkout', to: 'home#checkout'




  root to: 'home#index'


end

app/models/Brand.rb
class Brand < ApplicationRecord
  has_many :shoes
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shoes
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :shoes
end
  

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_shoe.rb
class OrderShoe < ApplicationRecord
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  paginates_per 50
  has_one_attached :image
  belongs_to :color
  belongs_to :brand
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :trackable, :confirmable, :lockable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_commit :send_welcome_email, on: :create

  def send_welcome_email
    MailJob.set(wait: 5.second).perform_later(id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
  def index
    @shoe= Shoe.all
  end

  def show

    @shoe = Shoe.find_by(id: params[:id]) if params[:id].present?
  end
  def delete
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def checkout
    before_action :authenticate_user!
  end


  def wishlist
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index


    @shoes = Shoe.all

  

    @shoes = @shoes.where("name LIKE ? ", "%#{params[:name]}%") if params[:name].present?

    @shoes = if params[:price] == 'DESC'
         @shoes.order(price: :desc)
      elsif params[:price] == 'ASC'
          @shoes.order(price: :asc)
      else
        @shoes.order(created_at: :desc)
      end

    @shoes = @shoes.where(suitable: params[:suitable]
      )if params[:suitable].present?

      @shoes = @shoes.where(brand: params[:brand])if params[:brand].present?




  end

  def show
    @shoe = Shoe.find_by(id: params[:id]) if params[:id].present?
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/index.html.erb
<br>
<div class="container">
  <%= form_tag search_index_path,method: :get do %>
  <div class="row justify-content-md-center">
    <%= label_tag :sort, "Sort By :" %>
    <div class="col-2" >
            <%= select_tag :price,options_for_select([['price',''],['High To Low','DESC'],['Low To High','ASC'],['New Arrive',' ']],params[:price]),class: "form-control form-control-lg " %>
            <%= hidden_field_tag(:name, params[:name] ,class: "form-control search")%>
            <%= hidden_field_tag(:suitable, params[:suitable] ,class: "form-control search")%>
    </div>
    <table>
      <tr>
        <td>
          <%= check_box_tag(:brand,'1',params[:price]) %>
          <%= label_tag :brand, 'adidas' %></td>
        <td>
           <%= check_box_tag(:brand,'2',params[:price]) %>
           <%= label_tag :brand, 'bata' %></td>
        <td>
          <%= check_box_tag(:brand,'3',params[:price]) %>
          <%= label_tag :brand, 'nike' %>
        </td>
      </tr>

      <tr>
        <td>
          <%= check_box_tag(:brand,'4',params[:price]) %>
          <%= label_tag :brand,'puma' %>
        </td>
        <td>
          <%= check_box_tag(:brand,'5',params[:price]) %>
          <%= label_tag :brand,'woodland' %>
        </td>
        <td>
          <%= check_box_tag(:brand,'7',params[:price]) %>
          <%= label_tag :brand,'reebok' %>
        </td>
      </tr>
    </table>
        <div class="col-2 btn-group" >
            <%= submit_tag  "search",class:"btn-sm btn-light" %>
        </div>
    </div>
    <% end %>
</div>



  <div class="colorlib-product">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
          <h2>View All Products</h2>
        </div>
      </div>

      <div class="row row-pb-md">
        <% if @shoes.present? %>
            <% @shoes.each do |shoe| %>
              <div class="col-md-3 col-lg-3 mb-4 text-center">
                <div class="product-entry bprice">
                  <a href="<%= search_path(id: shoe.id)=%>",class="prod-img">
                    <%= image_tag shoe.image,class: 'img-fluid'%>
                  </a>
                  <div class="desc">
                    <h2><a href="#"><%= shoe.name%></a></h2>
                    <h2><a href="#"><%= shoe.brand.name%></a></h2>
                    <span class="price"><%= shoe.price %></span>
                    <span><%=  shoe.suitable %></span>
                  </div>
                </div>
              </div>
            <% end %>
        <% else %>
          <div class="col-sm-8 offset-sm-2 text-center ">
            <h2>Shoes Not Exist!!</h2>
          </div>
        <% end %>
      </div>
      
    </div>
  </div>

  <div class="colorlib-partner">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
          <h2>Trusted Partners</h2>
        </div>
      </div>
      <div class="row">
        <div class="col partner-col text-center">
        <%= image_tag "brand-1.jpg",:class => 'img-fluid' %>
        </div>
        <div class="col partner-col text-center">
          <%= image_tag "brand-2.jpg",:class => 'img-fluid' %>
        </div>
        <div class="col partner-col text-center">
          <%= image_tag "brand-3.jpg",:class => 'img-fluid' %>
        </div>
        <div class="col partner-col text-center">
          <%= image_tag "brand-4.jpg",:class => 'img-fluid' %>
        </div>
        <div class="col partner-col text-center">
          <%= image_tag "brand-5.jpg",:class => 'img-fluid' %>
        </div>
      </div>
    </div>
  </div>
<div class="">

</div>

<br><br>

app/views/search/show.html.erb
<div class="breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col">
						<p class="bread"><span><a href="index.html">Home</a></span> / <span>Product Details</span></p>
					</div>
				</div>
			</div>
		</div>


		<div class="colorlib-product">
			<div class="container">
            <% if @shoe.present? %>
				<div class="row row-pb-lg product-detail-wrap">

					<div class="col-sm-8">
        		<div class="item">

								<div class="product-entry border">
								<a href="#" class="prod-img">
								<%= image_tag @shoe.image,:class => 'img-fluid',:alt => 'Free html5 bootstrap 4 template' %>
									</a>
								</div>

							</div>
					</div>
        		<div class="col-sm-4">
  						<div class="product-desc">
  							<h3><%= @shoe.name %></h3>
  							<p class="price">
  								<span><%= @shoe.price %></span>
                  <span>suitable for <%= @shoe.suitable %></span>
                  <h2><%= @shoe.color.name%></h2>
                    <h2>From <%= @shoe.brand.name%></h2>
  								<span class="rate">
  									<i class="icon-star-full"></i>
  									<i class="icon-star-full"></i>
  									<i class="icon-star-full"></i>
  									<i class="icon-star-full"></i>
  									<i class="icon-star-half"></i>
  									(74 Rating)
  								</span>

                <div class="size-wrap">
								  <div class="block-26 mb-2">
									  <h4>Size</h4>
				               <ul>
				                  <li><a href="#">7</a></li>
				                  <li><a href="#">7.5</a></li>
				                  <li><a href="#">8</a></li>
				                  <li><a href="#">8.5</a></li>
				                  <li><a href="#">9</a></li>
				                  <li><a href="#">9.5</a></li>
				                  <li><a href="#">10</a></li>
				                  <li><a href="#">10.5</a></li>
				                  <li><a href="#">11</a></li>
				                  <li><a href="#">11.5</a></li>
				                  <li><a href="#">12</a></li>
				                  <li><a href="#">12.5</a></li>
				                  <li><a href="#">13</a></li>
				                  <li><a href="#">13.5</a></li>
				                  <li><a href="#">14</a></li>
				               </ul>
				          </div>
							</div>
                     <div class="input-group mb-4">
                     	<span class="input-group-btn">
                        	<button type="button" class="quantity-left-minus btn"  data-type="minus" data-field="">
                           <i class="icon-minus2"></i>
                        	</button>
                    		</span>
                     	<input type="text" id="quantity" name="quantity" class="form-control input-number" value="1" min="1" max="100">
                     	<span class="input-group-btn ml-1">
                        	<button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                             <i class="icon-plus2"></i>
                         </button>
                     	</span>
                  	</div>

    						</div>
    					</div>
    				</div>

				<div class="row">
					<div class="col-sm-12">
						<div class="row">
							<div class="col-md-12 pills">
								<div class="bd-example bd-example-tabs">
								  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
								    <li class="nav-item">
								      <a class="nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-expanded="true">Description</a>
								    </li>
							    </ul>
								  <div class="tab-content" id="pills-tabContent">
								    <div class="tab-pane border fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab">
                      	<span><%= @shoe.description %></span>
								    </div>
								  </div>
								</div>
				       </div>
						</div>
					</div>
				</div>
        <% end %>
			</div>
		</div>