config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'show/show'
  resources :search
  resources :home
  resources :carts
  resources :orders, only: [:index,:create ,:delete]


  get 'about', to: 'home#about', as: :about
  get 'contact',to: 'home#contact',as: :contact
  get 'checkout', to: 'home#checkout'




  root to: 'home#index'


end

app/models/Brand.rb
class Brand < ApplicationRecord
  has_many :shoes
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shoes
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :shoes
end
  

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_shoe.rb
class OrderShoe < ApplicationRecord
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  paginates_per 50
  has_one_attached :image
  belongs_to :color
  belongs_to :brand
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :trackable, :confirmable, :lockable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_commit :send_welcome_email, on: :create

  def send_welcome_email
    MailJob.set(wait: 5.second).perform_later(id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
  def index
    @shoe= Shoe.all
  end

  def show

    @shoe = Shoe.find_by(id: params[:id]) if params[:id].present?
  end
  def delete
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def checkout
    before_action :authenticate_user!
  end


  def wishlist
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer id="colorlib-footer" role="contentinfo">
  <div class="container">
    <div class="row row-pb-md">
      <div class="col footer-col colorlib-widget">
        <h4>About Footwear</h4>
        <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>
        <p>
          <ul class="colorlib-social-icons">
            <li><a href="#"><i class="icon-twitter"></i></a></li>
            <li><a href="#"><i class="icon-facebook"></i></a></li>
            <li><a href="#"><i class="icon-linkedin"></i></a></li>
            <li><a href="#"><i class="icon-dribbble"></i></a></li>
          </ul>
        </p>
      </div>
      <div class="col footer-col colorlib-widget">
        <h4>Customer Care</h4>
        <p>
          <ul class="colorlib-footer-links">
            <li><a href="#">Contact</a></li>
            <li><a href="#">Returns/Exchange</a></li>
            <li><a href="#">Gift Voucher</a></li>
            <li><a href="#">Wishlist</a></li>
            <li><a href="#">Special</a></li>
            <li><a href="#">Customer Services</a></li>
            <li><a href="#">Site maps</a></li>
          </ul>
        </p>
      </div>
      <div class="col footer-col colorlib-widget">
        <h4>Information</h4>
        <p>
          <ul class="colorlib-footer-links">
            <li><a href="#">About us</a></li>
            <li><a href="#">Delivery Information</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Order Tracking</a></li>
          </ul>
        </p>
      </div>

      <div class="col footer-col">
        <h4>News</h4>
        <ul class="colorlib-footer-links">
          <li><a href="blog.html">Blog</a></li>
          <li><a href="#">Press</a></li>
          <li><a href="#">Exhibitions</a></li>
        </ul>
      </div>

      <div class="col footer-col">
        <h4>Contact Information</h4>
        <ul class="colorlib-footer-links">
          <li>291 South 21th Street, <br> Suite 721 New York NY 10016</li>
          <li><a href="tel://1234567920">+ 1235 2355 98</a></li>
          <li><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
          <li><a href="#">yoursite.com</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="copy">
    <div class="row">
      <div class="col-sm-12 text-center">
        <p>
          <span>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This site is made with <i class="icon-heart" aria-hidden="true"></i>
          </span>
          </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="colorlib-nav" role="navigation">
  <div class="top-menu">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 col-md-9">
          <div id="colorlib-logo">Footwear</div>
        </div>
        <div class="col-sm-5 col-md-3">
          <div class="form-group">
            <%= form_with url: search_index_path,  class: 'search-wrap navbar-form navbar-left', local: true, method: :get do |form| %>
            <%= text_field_tag(:name, params[:name] ,class: "form-control search",placeholder:t('menu.Search'))%>
            <%= hidden_field_tag(:suitable, params[:suitable] ,class: "form-control search")%>
            <button  class="btn btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 text-left menu-1">
          <ul>
            <li class=" has-dropdown active">
              <%= link_to t('menu.home'), root_path %>
              <ul class="dropdown">
                <li><%= link_to t('menu.Shopping cart'), carts_path %></li>
                <li><%= link_to t('menu.Order complete'), orders_path %></li>
                <li><%= link_to t('menu.Checkout'), new_user_session_path %></li>
              </ul>
            </li>
            <li><%= link_to  t('menu.Men'), search_index_path(suitable: 'men',name: params[:name]) %></li>
            <li><%= link_to  t('menu.Women'), search_index_path(suitable: 'women',name: params[:name])%></li>
            <li><%= link_to  t('menu.About'), about_path%></li>
            <li><%= link_to t('menu.Contact'),contact_path%></li>
            <li>
              <% if current_user %>
              <%= link_to t('menu.LogOut'), destroy_user_session_path, method: :delete %>
              <% else %>
              <%= link_to t('menu.Login'), new_user_session_path %>
              <% end %>
            </li>
            <li class="cart"><i class="icon-shopping-cart"></i><%= link_to t('menu.Cart'), carts_path%></li>
            <div class="btn-group">
              <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              language
              </button>
              <div class="dropdown-menu">
                <li><%= link_to 'Gujarati',locale: "gu"%></li>
                <li><%= link_to 'English',locale: "en" %></li>
              </div>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="sale">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-center">
          <div class="row">
            <div class="owl-carousel2">
              <div class="item">
                <div class="col">
                  <h3><a href="#">25% off (Almost) Everything! Use Code: Summer Sale</a></h3>
                </div>
              </div>
              <div class="item">
                <div class="col">
                  <h3><a href="#">Our biggest sale yet 50% off all summer shoes</a></h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionFeet.com</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="colorlib-loader"></div>

    <div id="page">
      <%= render 'layouts/header' %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>